// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3vB0iDRlz1fu89gMo_teuxX3Del_qFM',
    appId: '1:90959011203:web:8134fca7a90bf6cfddaab6',
    messagingSenderId: '90959011203',
    projectId: 'socialmediaautomation-56e23',
    authDomain: 'socialmediaautomation-56e23.firebaseapp.com',
    storageBucket: 'socialmediaautomation-56e23.firebasestorage.app',
    measurementId: 'G-C7CR86255M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOc5AWelBzsJ39Uv6RKxdE_pBDTpNecCI',
    appId: '1:90959011203:android:0b34ba640a6653abddaab6',
    messagingSenderId: '90959011203',
    projectId: 'socialmediaautomation-56e23',
    storageBucket: 'socialmediaautomation-56e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VPnBwebD_QRgbjMQJ_sEMRG4gbDPZWM',
    appId: '1:90959011203:ios:b973ed62b1417fdbddaab6',
    messagingSenderId: '90959011203',
    projectId: 'socialmediaautomation-56e23',
    storageBucket: 'socialmediaautomation-56e23.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VPnBwebD_QRgbjMQJ_sEMRG4gbDPZWM',
    appId: '1:90959011203:ios:b973ed62b1417fdbddaab6',
    messagingSenderId: '90959011203',
    projectId: 'socialmediaautomation-56e23',
    storageBucket: 'socialmediaautomation-56e23.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaAutomation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp3vB0iDRlz1fu89gMo_teuxX3Del_qFM',
    appId: '1:90959011203:web:b4b8895ee8e2be34ddaab6',
    messagingSenderId: '90959011203',
    projectId: 'socialmediaautomation-56e23',
    authDomain: 'socialmediaautomation-56e23.firebaseapp.com',
    storageBucket: 'socialmediaautomation-56e23.firebasestorage.app',
    measurementId: 'G-XB7YVQ8GG0',
  );

}